package com.alex.springmvc.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.alex.springmvc.mybatis.entity.Person;
import com.alex.springmvc.mybatis.entity.PersonExample;

/**
 * 通过MyBatis Generator自动生成
 * MyBatis的Mapper
 * 
 * @author xiaoming
 *
 */
public interface IPersonDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int updateByExampleSelective(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int updateByExample(@Param("record") Person record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table person
     *
     * @mbg.generated Tue Aug 08 21:39:42 CST 2017
     */
    int updateByPrimaryKey(Person record);
    
    public Person getPersonJoinPost(int personId);
    
    public Person getPersonByIf(@Param("id") int id,@Param("name") String name,@Param("website") String website);

    public Person getPersonByWhereWrong(@Param("id") int id,@Param("name") String name,@Param("website") String website);

    public Person getPersonByWhere(@Param("id") int id,@Param("name") String name,@Param("website") String website);

    public Person getPersonByChoose(@Param("id") int id,@Param("name") String name,@Param("website") String website);
}